### ISSUE TITLE
Margin calculation wrong again?

### ISSUE THREAD

**Issue by edrickrenan** [whittlem/pycryptobot#148]
**Describe the bug**
Hey @whittlem, after pulling the changes this morning I faced that same margin calculation issue we investigated yesterday.

One interesting thing is that it happened when the granularity changed from 15m to 1h.
```
05/11/2021 09:30:25 AM - DEBUG: 2021-05-11 08:30:00 | BCHUSDT | 15m | Close: 1340.11 | ^ EMA12/26: 1342.15 > 1341.61 ^ | ^ MACD: 0.54 > -0.41 ^ | WAIT | Last Action: BUY | -9.58% (delta: -134.47)
05/11/2021 09:30:25 AM - DEBUG: 2021-05-11 08:30:00 | BCHUSDT | 15m | Close: 1340.11 | ^ EMA12/26: 1342.15 > 1341.61 ^ | ^ MACD: 0.54 > -0.41 ^ | WAIT | Last Action: BUY | -9.58% (delta: -134.47)
05/11/2021 09:33:07 AM - DEBUG: 2021-05-11 08:00:00 | BCHUSDT | 1h | Close: 1343.89 | v EMA12/26: 1350.5 < 1372.64 v | v MACD: -22.14 < -21.51 v | WAIT | Last Action: BUY | -1089292.67% (delta: -132.11)
05/11/2021 09:33:07 AM - DEBUG: 2021-05-11 08:00:00 | BCHUSDT | 1h | Close: 1343.89 | v EMA12/26: 1350.5 < 1372.64 v | v MACD: -22.14 < -21.51 v | WAIT | Last Action: BUY | -1089292.67% (delta: -132.11)
```

```
05/11/2021 09:31:45 AM - DEBUG: 2021-05-11 08:30:00 | ETHUSDT | 15m | Close: 3927.36 | ^ EMA12/26: 3927.49 > 3920.52 ^ | ^ MACD: 6.96 > 1.91 ^ | WAIT | Last Action: BUY | -0.98% (delta: -18.78)
05/11/2021 09:31:45 AM - DEBUG: 2021-05-11 08:30:00 | ETHUSDT | 15m | Close: 3927.36 | ^ EMA12/26: 3927.49 > 3920.52 ^ | ^ MACD: 6.96 > 1.91 ^ | WAIT | Last Action: BUY | -0.98% (delta: -18.78)
05/11/2021 09:33:08 AM - DEBUG: 2021-05-11 08:00:00 | ETHUSDT | 1h | Close: 3926.72 | v EMA12/26: 3935.47 < 3961.11 v | v MACD: -25.64 < -18.96 v | WAIT | Last Action: BUY | -7786601.81% (delta: -19.56)
05/11/2021 09:33:08 AM - DEBUG: 2021-05-11 08:00:00 | ETHUSDT | 1h | Close: 3926.72 | v EMA12/26: 3935.47 < 3961.11 v | v MACD: -25.64 < -18.96 v | WAIT | Last Action: BUY | -7786601.81% (delta: -19.56)

```

**Comment by whittlem** [comment]
Is this fixed now after the last update?

**Comment by whittlem** [comment]
Is this resolved now?

**Comment by edrickrenan** [comment]
I don't think there was any change to fix that... The last one I saw was reverted, and the issue is still happening

**Comment by whittlem** [comment]
I'm not able to re-create this issue for Coinbase Pro or Binance which makes it difficult to fix.
