### ISSUE TITLE
Telegram client ID regex

### ISSUE THREAD

**Issue by AdrianDonohoe** [whittlem/pycryptobot#58]
Hi Michael,

great job on the bot. Thanks.

My telegram client ID starts with a dash  followed by digits. So  it fails the regex in the PyCyrpoBot and Telegram models.

re.compile(r"^\d{7,10}$")

To make it work I changed to : 
re.compile(r"^-\d{7,10}$")

I put the telegram bot in group with myself, perhaps this is the reason there is  a dash at the beginning of the client id.

BR,
Adrian.

**Comment by whittlem** [comment]
Thanks, your regex would make the leading dash mandatory.

I've pushed this update now:
re.compile(r"^\-*\d{7,10}$")

Mine still works with an all numeric client id and I suspect yours will work now too.

**Comment by AdrianDonohoe** [comment]
Hi Michael,

could you put that update into models/Telegram.py also ?  There is a regex check in their too which is still throwing an exception.

BR,
Adrian.
